### ISSUE TITLE
Missing libretto tags in the metadata table

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/itadracor#8]
The metadata table does not show up any libretti in the corpus, despite 15-20 texts actually belonging to that category (e.g. Da Ponte's [_Don Giovanni_](https://dracor.org/api/corpora/ita/play/da-ponte-don-giovanni/tei)) .

It might be due to the fact that the Italian corpus, like the French one, has some kind of legacy markup in the `<textClass>` element like this

```
<keywords scheme="#CDD">
  <term>782.12 - LIBRETTI D'OPERA</term>
</keywords>
```
instead of the now established

```
<keywords>
  <term type="genreTitle">Libretto</term>
</keywords>
```

The metadata table for the French one identifies all libretti, though, so it might just be that here a trigger linked to the "libretti" word in `<term>` is missing, or something like that.

**Comment by cmil** [comment]
For libretti the `textClass` markup should look like this:

```xml
<textClass>
  <keywords>
    <term type="genreTitle">Libretto</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q131084</classCode>
</textClass>
```

The important part is actually the `classCode` element which is expected to provide a Wikidata ID for a genre. The keywords are currently not really used by the API and are there for historical reasons.

**Comment by lucagiovannini7** [comment]
Cool, shall I/we try to add the `classCode` element then?

**Comment by cmil** [comment]
@lucagiovannini7 I would say go for it. However, some research might be necessary to find all libretti in the corpus since the three Da Ponte libretti are the only ones marked as such. None of the Metastasio texts for instance is.
